local M = {}

M.entries = {
  { label = "OpenAllFiles", command = "OpenAllFiles" },
  { label = "OpenFilesFromClipboard", command = "OpenFilesFromClipboard" },
  { label = "CopyCurrentPath", command = "CopyCurrentPath" },
  { label = "CopyCurrentPathWithLineNumber", command = "CopyCurrentPathWithLineNumber" },
  { label = "CopyAbsolutePath", command = "CopyAbsolutePath" },
  { label = "CopyAllTabPath", command = "CopyAllTabPath" },
  { label = "CopyAllTabAbsolutePath", command = "CopyAllTabAbsolutePath" },
  { label = "OpenGitHubRepo", command = "OpenGitHubRepo" },
  { label = "OpenGitHubFileNormal", command = "OpenGitHubFileNormal" },
  { label = "QuitAll", command = "QuitAll" },
  { label = "LoadVIMRC", command = "LoadVIMRC" },
  { label = "MarkdownPreviewITerm", command = "MarkdownPreviewITerm" },
  { label = "MarkdownPreviewITermStop", command = "MarkdownPreviewITermStop" },
  { label = "SwaggerPreview", command = "SwaggerPreview" },
  { label = "SwaggerPreviewStop", command = "SwaggerPreviewStop" },
  { label = "DeleteBuffers", command = "DeleteBuffers" },
  { label = "ClearAllBuffers", command = "ClearAllBuffers" },
  { label = "SwapWindow", command = "SwapWindow" },
  { label = "PlugInstall", command = "PlugInstall" },
  { label = "PlugUpdate", command = "PlugUpdate" },
  { label = "PlugClean", command = "PlugClean" },
  { label = "PlugStatus", command = "PlugStatus" },
  { label = "DiffFile", command = "DiffFile" },
  { label = "Reload", command = "Reload" },
  { label = "CloseTabs", command = "CloseTabs" },
  { label = "CloseTabsRight", command = "CloseTabsRight" },
  { label = "CloseTabsLeft", command = "CloseTabsLeft" },
  { label = "MergeTab", command = "MergeTab" },
  { label = "SeparateTab", command = "SeparateTab" },
  { label = "CopyStatusMessage", command = "CopyStatusMessage" },
  { label = "StartCopyStatusMessages", command = "StartCopyStatusMessages" },
  { label = "FinishCopyStatusMessages", command = "FinishCopyStatusMessages" },
  { label = "StripAnsi", command = "StripAnsi" },
}

return M
